### ISSUE TITLE
Remove GuzzleHttp Dependency

### ISSUE THREAD

**Issue by mechawrench** [mechawrench/cafcp-hydrogen-station-fuel-status#3]
This dependency was initially used in development but abandoned, clean up and remove the dependency and any references to it.

**Comment by bluemorbo** [comment]
*Disclaimer: I'm an OSS newbie*

I'm happy to pick this up. One thing I've noticed while digging around is that while `CafcpHydrogenStationFuelStatus.php` doesn't use Guzzle's functionality outside of the constructor, the test `it_returns_a_station_status` uses it to mock a response (nice touch, BTW).

Given the request is now being made via `file_get_contents()`, I'd suggest the best course of action would be to introduce an CAFCP API class that only deals with fetching the content (and thus easy to mock in tests), then dependency inject it into the constructor of `CafcpHydrogenStationFuelStatus`. Finally, make the static method non-static, so it uses the new API class to make its requests. This removes the dependency on GuzzleHTTP, but makes the code itself more testable. Unfortunately, this would result in a breaking change.

The alternative is that we stick with GuzzleHTTP and remove references to `file_get_contents()` (which is significantly less work, as rules out the need for a breaking change / major version bump)

I'm open to alternative suggestions though if you have a particular preference on implementation detail :+1:
